// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: orders/message.proto

/* eslint-disable */
import { type ItemType } from "../common/item_types";
import { type ShipmentType } from "../common/shipment_types";

export const protobufPackage = "proto_example.orders";

export interface Order {
  id: number;
  itemTypes: ItemType[];
  shipmentType: ShipmentType | undefined;
}
