// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.27.1
// source: common/chart_item.proto

/* eslint-disable */

export const protobufPackage = "";

export interface ChartItem {
  count: string;
  /** 创建时间 */
  startTime: Date | undefined;
}
