// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.3
//   protoc               v5.28.2
// source: common/chart_item.proto

/* eslint-disable */

export const protobufPackage = "";

export interface ChartItem {
  count: string;
  /** 开始时间 如果是使用Timestamp，将 Date 对象转换为 Timestamp 对象才能传输，为了减少不必要的操作，使用string。 */
  startTime: string;
}
