// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: common/item_types.proto

/* eslint-disable */

export const protobufPackage = "proto_example.common.items";

export enum ItemType {
  DEFAULT = 0,
  SUPERIOR = 1,
  FLAWLESS = 2,
  UNRECOGNIZED = -1,
}
