// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: common/shipment_types.proto

/* eslint-disable */

export const protobufPackage = "proto_example.common.shipments";

export interface ShipmentType {
  from: string;
  to: string;
  carrier: string;
}
