// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.1
// source: protos/auth.proto

/* eslint-disable */

export const protobufPackage = "authproto";

export interface LoginRequest {
  account: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  userId: number;
  account: string;
  expiresIn: number;
}

export interface ValidateUserRequest {
  userId: number;
}

export interface AuthService {
  login(request: LoginRequest): Promise<LoginResponse>;
  validateUser(request: ValidateUserRequest): Promise<LoginResponse>;
}
