// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: log.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "logproto";

export interface LogRequest {
  /** 唯一索引 */
  id: number;
  /** 报告类型 */
  reportsType: string;
  /** 错误 UUID */
  errorUUid: string;
  /** 站点 ID */
  siteId: string;
  /** 模型引用类型 */
  onModel: string;
  /** 内容引用 */
  doce:
    | { [key: string]: any }
    | undefined;
  /** 日志类别 */
  category: string;
  /** 用户 ID */
  userId: string;
  /** 标题 */
  title: string;
  /** 路径 */
  path: string;
  /** URL */
  href: string;
  /** 方法 */
  method: string;
  /** 请求 URL */
  url: string;
  /** 请求体参数 */
  body:
    | { [key: string]: any }
    | undefined;
  /** 请求参数 */
  params:
    | { [key: string]: any }
    | undefined;
  /** 响应 */
  response:
    | Response
    | undefined;
  /** 错误信息 */
  value: string;
  /** IP 地址 */
  ip: string;
  /** 创建时间 */
  createAt:
    | Date
    | undefined;
  /** 更新时间 */
  updateAt:
    | Date
    | undefined;
  /** 追踪 ID */
  traceId: string;
  /**  */
  monitorId: string;
  /**  */
  nodeId: string;
  /**  */
  duration: number;
  entryType: string;
  startTime: number;
  fmpTime: number;
  cacheRate: string;
  /** 请求信息 */
  requestInfo:
    | RequestInfo
    | undefined;
  /** DNS 时间 */
  dns: number;
  /** DOM 解析时间 */
  domParse: number;
  /** DOM 准备时间 */
  domReady: number;
  /** 首字节时间 */
  firstByte: number;
  /** 首次图像可见时间 */
  fp: number;
  /** 加载时间 */
  load: number;
  /** 资源时间 */
  res: number;
  /** 是否使用 SSL */
  ssl: boolean;
  /** TCP 时间 */
  tcp: number;
  /** 传输时间 */
  trans: number;
  /** TTFB（首次字节时间） */
  ttfb: number;
  /** 总时间 */
  total: number;
  endTime: number;
  interactionTime: number;
  loadedTime: number;
  loadingTime: number;
  queryUrl: string;
  requestTime: number;
  responseTime: number;
  status: number;
  statusText: string;
  errorType: string;
  content: string;
  /** 元数据 */
  meta: Meta | undefined;
}

export interface Meta {
  body: { [key: string]: any } | undefined;
  endTime: number;
  interactionTime: number;
  loadedTime: number;
  loadingTime: number;
  method: string;
  params: { [key: string]: any } | undefined;
  queryUrl: string;
  requestTime: number;
  response: Response | undefined;
  responseTime: number;
  status: number;
  statusText: string;
  url: string;
}

export interface RequestInfo {
  /** 内容下载 */
  contentDownload: number;
  /** DNS 查找 */
  dnsLookup: number;
  /** 初始连接 */
  initialConnect: number;
  /** 发起者类型 */
  initiatorType: string;
  /** 是否缓存 */
  isCache: boolean;
  /** 请求 URL */
  name: string;
  /** 请求时长 */
  requestDuration: number;
  /** 响应结束时间 */
  responseEnd: number;
  /** 是否使用 SSL */
  ssl: boolean;
  /** 开始时间 */
  startTime: number;
  /** TTFB（首次字节时间） */
  timeToFirstByte: number;
  /** 传输大小 */
  transferSize: number;
}

/** 响应消息定义 */
export interface Response {
  code: number;
  msg: string;
  data: { [key: string]: any } | undefined;
}

export interface LogResponse {
}

export interface LogService {
  /** 保存走kafka, 不过两种都支持==== */
  saveLog(request: LogRequest): Observable<LogResponse>;
}
