// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.3
//   protoc               v5.28.2
// source: site.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "siteproto";

export interface SiteRequest {
  id: number;
  name: string;
  isApi: number;
  reportUrl: string;
  state: number;
}

export interface SiteResponse {
  id: number;
}

export interface SiteService {
  saveSite(request: SiteRequest): Observable<SiteResponse>;
}
