// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: site.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "siteproto";

export interface SiteRequest {
  id: number;
  name: string;
  isApi: number;
  reportUrl: string;
  state: number;
}

export interface SiteResponse {
}

export interface SiteService {
  createSite(request: SiteRequest): Observable<SiteResponse>;
}
