// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.27.1
// source: user.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "userproto";

export interface getBooksRequest {
}

export interface getUsersResponse {
  users: User[];
}

export interface User {
  id: number;
  name: string;
  createdAt: string;
}

export interface Order {
  id: number;
  itemTypes: number[];
}

export interface UserService {
  getUsers(request: getBooksRequest): Observable<getUsersResponse>;
  find(request: Order): Promise<Order>;
  sync(request: Observable<Order>): Observable<Order>;
  streamReq(request: Observable<Order>): Promise<Order>;
  streamReqCall(request: Observable<Order>): Promise<Order>;
}
