// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.8
// source: protos/user.proto

/* eslint-disable */

export const protobufPackage = "userproto";

export interface getBooksRequest {
}

export interface getUsersResponse {
  users: User[];
}

export interface User {
  id: number;
  name: string;
}

export interface UserService {
  getUsers(request: getBooksRequest): Promise<getUsersResponse>;
}
