/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace userproto {
    export interface UserService {
        getUsers(
            data: getBooksRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<getUsersResponse>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface getBooksRequest {
    }
    export interface getUsersResponse {
        users?: userproto.User[];
    }
    export interface User {
        id?: number;
        name?: string;
    }
}

